### ISSUE TITLE
Logo proposal for DecisionTree

### ISSUE THREAD

**Issue by memoryskull** [juliangaal/dtree#14]
Hi! @juliangaal 

I'm interested in collaborating with this project by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by juliangaal** [comment]
Sure, what's the kicker? What's your motivation? 
I am not sure if this project will ever become more than my hobby project, but good logos are always nice :D

**Comment by memoryskull** [comment]
Hi @juliangaal 
It motivates me to contribute with open source projects in addition to refining my design skills and improving my portfolio.

**Comment by memoryskull** [comment]
@juliangaal 
It would be very useful if you would provide me with the most information and if you want some features or specific colors.

**Comment by memoryskull** [comment]
I have a doubt about the license of your repository?

**Comment by juliangaal** [comment]
it should be minimalistic. Take a look at the tree in the readme. Maybe you could design a logo of an *actual* tree, with the nodes and edges like in the decision tree?

I don't mean to be rude, but what does the license mean for you? why does it matter?

**Comment by memoryskull** [comment]
Hi @juliangaal 
Perfect soon my logo proposal will be presented.
With respect to the license, I refer to copyright policies.
Good day.

**Comment by juliangaal** [comment]
Well, that's nice that you "refer to them". Tell me, Why does the license matter to you?

**Comment by memoryskull** [comment]
@juliangaal  Because it must be free.

**Comment by juliangaal** [comment]
Thanks for the suggested help, but am I no longer interested, as you couldn't concisely answer my questions. Closing now.
